const express = require('express');
const mongoose = require('mongoose');
const path = require('path');
require('dotenv').config();

const app = express();
app.use(express.json());

// Admin Panel के लिए Static Files सेटअप
app.use(express.static(path.join(__dirname)));

// 1. MongoDB Connection
mongoose.connect(process.env.MONGO_URI)
  .then(() => console.log('MongoDB Connected Successfully!'))
  .catch(err => console.log('MongoDB Connection Error: ', err));

// 2. Database Schema
const keySchema = new mongoose.Schema({
  key: { type: String, required: true, unique: true },
  expiry: { type: Date, required: true },
  maxDevices: { type: Number, default: 1 },
  devices: { type: [String], default: [] },
  status: { type: String, default: 'Active' } 
});

const LicenseKey = mongoose.model('LicenseKey', keySchema);

// Admin Panel (index.html) खोलें
app.get('/', (req, res) => {
  res.sendFile(path.join(__dirname, 'index.html'));
});

// ==========================================
// API 1: Generate Key
// ==========================================
app.post('/api/generate', async (req, res) => {
  try {
    const { key, hoursValid, maxDevices } = req.body;
    const expiryDate = new Date(Date.now() + (hoursValid || 24) * 60 * 60 * 1000);

    const newKey = new LicenseKey({
      key: key,
      expiry: expiryDate,
      maxDevices: maxDevices || 1,
      status: 'Active'
    });

    await newKey.save();
    res.json({ success: true, message: 'Key generated successfully!', data: newKey });
  } catch (error) {
    res.status(500).json({ success: false, error: error.message });
  }
});

// ==========================================
// API 2: Verify Key
// ==========================================
app.post('/api/verify', async (req, res) => {
  try {
    const { key, deviceId } = req.body;
    if (!key || !deviceId) return res.status(400).json({ success: false, message: 'Required fields missing!' });

    const foundKey = await LicenseKey.findOne({ key: key });
    if (!foundKey) return res.json({ success: false, message: 'Invalid Key!' });
    if (foundKey.status === 'Banned') return res.json({ success: false, message: 'Key is Banned!' });
    if (new Date() > new Date(foundKey.expiry)) {
      foundKey.status = 'Expired';
      await foundKey.save();
      return res.json({ success: false, message: 'Key has Expired!' });
    }

    if (foundKey.devices.includes(deviceId)) return res.json({ success: true, message: 'Key Verified!' });
    if (foundKey.devices.length >= foundKey.maxDevices) return res.json({ success: false, message: 'Device limit reached!' });

    foundKey.devices.push(deviceId);
    await foundKey.save();
    res.json({ success: true, message: 'Key Verified & Device registered!' });
  } catch (error) {
    res.status(500).json({ success: false, error: error.message });
  }
});

// ==========================================
// API 3: Ban Key
// ==========================================
app.post('/api/ban', async (req, res) => {
  try {
    const { key } = req.body;
    const foundKey = await LicenseKey.findOne({ key: key });
    if (!foundKey) return res.json({ success: false, message: 'Key not found!' });

    foundKey.status = 'Banned';
    await foundKey.save();
    res.json({ success: true, message: 'Key Banned successfully!' });
  } catch (error) {
    res.status(500).json({ success: false, error: error.message });
  }
});

// Server Start
const PORT = process.env.PORT || 10000;
app.listen(PORT, () => {
  console.log(`Server is running on port ${PORT}`);
});

// Reseller Login & Key Generation API
app.post('/api/reseller-generate', async (req, res) => {
  try {
    const { resellerUsername, key, hoursValid, maxDevices } = req.body;
    
    // 1. Reseller चेक करें
    const reseller = await Reseller.findOne({ username: resellerUsername });
    if (!reseller || reseller.credits <= 0) {
      return res.status(403).json({ success: false, message: 'Invalid Reseller or No Credits Left!' });
    }

    // 2. Key बनाएं
    const expiryDate = new Date(Date.now() + (hoursValid || 24) * 60 * 60 * 1000);
    const newKey = new LicenseKey({ key, expiry: expiryDate, maxDevices: maxDevices || 1, status: 'Active' });
    await newKey.save();

    // 3. Reseller का 1 क्रेडिट काट लें
    reseller.credits -= 1; 
    await reseller.save();

    res.json({ success: true, message: 'Key Generated by Reseller!', data: newKey, remainingCredits: reseller.credits });
  } catch (error) {
    res.status(500).json({ success: false, error: error.message });
  }
});
